spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bargain_buy_club
    username: marty
    password: iv!\CkQ=84AXMQ-
  data:
    rest:
      base-path: /api/v1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sendgrid:
    api-key: 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
allowed:
  origin: http://localhost:3000